project_id = "dzjglpfhwmgbsprpgzbk"

[functions.manage-user]
verify_jwt = false

[functions.analyze-survey]
verify_jwt = true

[functions.suggest-questions]
verify_jwt = false

[functions.analyze-text-responses]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

